framework:
  messenger:

    serializer:
      default_serializer: messenger.transport.symfony_serializer

    transports:
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          queues:
            customer-service: ~

    routing:
      'App\Common\Message\OrderCreated': async

    buses:
      default.bus:
        default_middleware:
          enabled: true
          allow_no_handlers: true
